# Concurrency 1: The Producer-Consumer Problem
#
# Makefile
#
# Group 37: Taylor Alexander Brown & Lucien Armand Tamdja Tamno
# Oregon State University
# CS 444: Operating Systems II
# Fall 2017

CC = gcc
CFLAGS =

test: test.S test.c
	$(CC) $(CFLAGS) test.S test.c -o test
