# Concurrency 2: The Dining Philosophers Problem
#
# File: Makefile
#
# Group 37: Taylor Alexander Brown & Lucien Armand Tamdja Tamno
# Oregon State University
# CS 444: Operating Systems II
# Fall 2017

CC = gcc
CFLAGS = -pthread -ggdb

all:
	$(CC) $(CFLAGS) concurrency2.c -o concurrency2
