# Build Project 1 Report
#
# Makefile
#
# Group 37: Taylor Alexander Brown & Lucien Armand Tamdja Tamno
# Oregon State University
# CS 444: Operating Systems II
# Fall 2017

all:
	pdflatex report.ltx
	pdflatex report.ltx
